### ISSUE TITLE
Add Text Field Capabilities

### ISSUE THREAD

**Issue by jasoneminyard** [jasoneminyard/blog#53]
To add a code block feature in a `form.text_field`, you can allow users to enter text with special markers or formatting that represents code, and then render it as a code block on the front-end.

Here’s an approach for both the form and display:

1. **Form Input:**
   - In your `form.text_field`, users could specify code blocks using special markers like triple backticks (```). For example:

   ```markdown
   This is regular text.
   
   ```ruby
   def hello
     puts "Hello, world!"
   end
   ```
   ```

2. **Backend Processing (Rails):**
   - You can capture the user input and store it in a database as-is. No changes needed here.
   
3. **Rendering (Front-End):**
   - To render the code block properly, you can use a library like Markdown parsers (`Redcarpet` gem) or just wrap code blocks manually.
   - For instance, with the Redcarpet gem:

   ```ruby
   gem 'redcarpet'
   ```

   In your controller/view:

   ```ruby
   markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, fenced_code_blocks: true)
   @article_with_code = markdown.render(@article.text_field_content)
   ```

4. **Styling the Code Block:**
   - Use CSS to style the code blocks:

   ```css
   pre {
     background-color: #f5f5f5;
     border: 1px solid #ccc;
     padding: 10px;
     overflow-x: auto;
   }
   
   code {
     font-family: monospace;
   }
   ```

This would allow users to type code blocks in their text field and see them formatted properly when displayed.
